import { Activity as ActivityIcon, ArrowRight, Building2, ClipboardCheck, Construction, CreditCard, MapPin, Smartphone } from 'lucide-react';
import type { DashboardData, Session } from '../../shared/types';
import type { AppPage } from '../components/Shell';
import { Badge, Button, Card, Kpi, Loading, SectionHeader } from '../components/UI';
import { ErrorBanner, formatDate, formatMoney, toneFor, useData } from './shared';

export default function Dashboard({session,navigate}:{session:Session;navigate:(page:AppPage)=>void}) {
  const {data,loading,error}=useData<DashboardData>('/api/dashboard',{kpis:[],projects:[],defects:[],payments:[],inspections:[],activities:[],tenants:[]});
  const role=session.user.role;
  const title=role==='tenant_admin'?'Cross-Tenant Oversight':role==='authority'?`Good morning, ${session.user.name.split(' ')[0]}`:role==='maker'?'My field work':role==='checker'?'Verification queue':'My infrastructure reports';
  const description=role==='tenant_admin'?'Aggregate visibility across all tenants for platform support and governance.':role==='authority'?`${session.tenant?.shortName} · Operations Dashboard`:role==='maker'?'Today’s assigned work, field actions and pending submissions.':role==='checker'?'Citizen validation, ATR, inspection and payment checks needing action.':'Report, track and follow every issue through resolution.';
  if(loading)return <Loading label="Preparing your role-specific dashboard"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow={role==='tenant_admin'?'DIGITAL INDIA PLATFORM':session.tenant?.shortName} title={title} description={description} action={role==='citizen'?<Button onClick={()=>navigate('citizen')} icon={<Smartphone size={17}/>}>Report an issue</Button>:undefined}/>
    <div className="kpi-grid">{data.kpis.map((kpi)=><Kpi key={kpi.label} {...kpi}/>)}</div>
    {role==='tenant_admin'?<TenantOverview data={data} navigate={navigate}/>:role==='citizen'?<CitizenOverview data={data} navigate={navigate}/>:<OperationsOverview data={data} role={role} navigate={navigate}/>} 
    <Card className="activity-card"><div className="card-heading"><div><ActivityIcon size={19}/><h2>Recent activity</h2></div>{role!=='citizen'&&<button onClick={()=>navigate('activity')}>View complete log <ArrowRight size={15}/></button>}</div><div className="timeline">{data.activities.map((item)=><div key={item.id}><span/><div><b>{item.action.replaceAll('_',' ')}</b><p>{item.detail}</p></div><time>{formatDate(item.timestamp)}</time></div>)}</div></Card>
  </div>;
}

function TenantOverview({data,navigate}:{data:DashboardData;navigate:(p:AppPage)=>void}){return <div className="dashboard-grid"><Card className="span-2"><div className="card-heading"><div><Building2 size={19}/><h2>Tenant estate</h2></div><button onClick={()=>navigate('tenants')}>Manage tenants <ArrowRight size={15}/></button></div><div className="tenant-card-grid">{data.tenants.map((tenant)=><button className="tenant-summary" key={tenant.id} onClick={()=>navigate('tenants')}><span style={{background:tenant.primaryColor}}>{tenant.shortName.slice(0,2)}</span><div><b>{tenant.shortName}</b><small>{tenant.type}</small><p>{tenant.assetTypes.map((a)=>a.name).join(' · ')||'Configuration pending'}</p></div><Badge tone={toneFor(tenant.status)}>{tenant.status}</Badge></button>)}</div></Card><Card><div className="card-heading"><div><MapPin size={19}/><h2>Citizen issue trend</h2></div></div><div className="bar-chart">{[34,47,41,63,54,76].map((n,i)=><div key={i}><i style={{height:`${n}%`}}/><span>{['Mar','Apr','May','Jun','Jul','Aug'][i]}</span></div>)}</div></Card></div>}

function OperationsOverview({data,role,navigate}:{data:DashboardData;role:string;navigate:(p:AppPage)=>void}){const pending=role==='checker'?data.defects.filter((d)=>d.checkerValidation==='Pending'||d.status==='ATR Submitted'):data.defects.slice(0,4);return <div className="dashboard-grid"><Card className="span-2"><div className="card-heading"><div><Construction size={19}/><h2>{role==='checker'?'Actions requiring verification':'Priority defects'}</h2></div><button onClick={()=>navigate('defects')}>Open defects <ArrowRight size={15}/></button></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Issue / location</th><th>Severity</th><th>Status</th><th>Due</th></tr></thead><tbody>{pending.map((d)=><tr key={d.id}><td><b className="mono">{d.id}</b></td><td><b>{d.title}</b><small>{d.location}</small></td><td><Badge tone={toneFor(d.severity)}>{d.severity}</Badge></td><td><Badge tone={toneFor(d.status)}>{d.status}</Badge></td><td>{formatDate(d.dueAt)}</td></tr>)}</tbody></table></div></Card><Card><div className="card-heading"><div><ClipboardCheck size={19}/><h2>Upcoming inspections</h2></div><button onClick={()=>navigate('inspections')}>View all</button></div><div className="compact-list">{data.inspections.slice(0,4).map((i)=><button key={i.id} onClick={()=>navigate('inspections')}><span className="list-icon"><ClipboardCheck size={17}/></span><div><b>{i.id} · {i.type}</b><small>{formatDate(i.scheduledAt)}</small></div><Badge tone={toneFor(i.status)}>{i.status}</Badge></button>)}</div></Card><Card><div className="card-heading"><div><CreditCard size={19}/><h2>Payment chain</h2></div><button onClick={()=>navigate('payments')}>View claims</button></div><div className="compact-list">{data.payments.slice(0,3).map((p)=><button key={p.id} onClick={()=>navigate('payments')}><span className="list-icon"><CreditCard size={17}/></span><div><b>{p.invoiceNo}</b><small>{formatMoney(p.amount)}</small></div><Badge tone={toneFor(p.status)}>{p.status}</Badge></button>)}</div></Card></div>}

function CitizenOverview({data,navigate}:{data:DashboardData;navigate:(p:AppPage)=>void}){return <div className="dashboard-grid"><Card className="span-2"><div className="card-heading"><div><Smartphone size={19}/><h2>My reports</h2></div><Button variant="secondary" onClick={()=>navigate('citizen')}>Report new issue</Button></div><div className="citizen-report-list">{data.defects.map((d)=><button key={d.id} onClick={()=>navigate('citizen')}><span className="report-pin"><MapPin size={18}/></span><div><b>{d.title}</b><small>{d.id} · {d.location}</small><div className="mini-progress"><i style={{width:`${['Under Checker Review','Assigned','In Progress','ATR Submitted','Resolved','Closed'].indexOf(d.status)*18+12}%`}}/></div></div><Badge tone={toneFor(d.status)}>{d.status}</Badge></button>)}</div></Card><Card className="citizen-help-card"><Smartphone/><h2>Your voice creates action</h2><p>Every accepted report is assigned to the responsible project, tracked against an SLA and verified before closure.</p><Button onClick={()=>navigate('citizen')}>Report an issue</Button></Card></div>}
