import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Crosshair, Eye, EyeOff, Layers3, MapPinned, Network, RadioTower } from 'lucide-react';
import type { Defect, GisOverview } from '../../shared/types';
import { Badge, Card, Loading, SectionHeader } from '../components/UI';
import MapplsMap from '../components/MapplsMap';
import { enrichLocation, type LocatedPoint } from '../location';
import { ErrorBanner, toneFor, useData } from './shared';

export default function GisPage() {
  const {data,loading,error}=useData<GisOverview>('/api/gis/overview',{configured:false,provider:'Mappls',layers:[],assets:[],defects:[],projects:[]});
  const [severity,setSeverity]=useState('All');
  const [selected,setSelected]=useState<Defect|null>(null);
  const [visibleLayers,setVisibleLayers]=useState<string[]>([]);
  const [picked,setPicked]=useState<LocatedPoint|null>(null);
  useEffect(()=>setVisibleLayers(data.layers.filter((layer)=>layer.visible).map((layer)=>layer.id)),[data.layers]);
  const pick=useCallback(async(point:{lat:number;lng:number})=>setPicked(await enrichLocation({...point,accuracyMeters:0,source:'Map selection' as const})),[]);
  const defects=useMemo(()=>data.defects.filter((defect)=>severity==='All'||defect.severity===severity),[data.defects,severity]);
  const layers=useMemo(()=>data.layers.map((layer)=>({...layer,visible:visibleLayers.includes(layer.id)})),[data.layers,visibleLayers]);
  if(loading)return <Loading label="Loading Mappls GIS workspace"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow="MAPPLS MAP + GIS OPERATIONS" title="Infrastructure Network Map" description="View defects, assets, project geofences and published network geometry together in one tenant-scoped operational map."/>
    <div className="gis-kpis"><Card><Network/><span><b>{data.layers.length}</b> Published network layers</span></Card><Card><MapPinned/><span><b>{data.assets.length}</b> Spatial assets</span></Card><Card><Crosshair/><span><b>{data.defects.filter((d)=>d.geofence?.within).length}</b> Geo-verified defects</span></Card><Card><RadioTower/><span><b>{data.configured?'Connected':'Credential pending'}</b> Mappls vector basemap</span></Card></div>
    <Card className="gis-toolbar"><div><Layers3/><b>Defect severity</b>{['All','Critical','High','Medium','Low'].map((item)=><button key={item} className={severity===item?'active':''} onClick={()=>setSeverity(item)}>{item}</button>)}</div><span>{defects.length} visible defects · {data.layers.reduce((sum,layer)=>sum+layer.featureCollection.features.length,0)} network features</span></Card>
    <div className="gis-workspace"><MapplsMap selectable onLocationSelect={pick} selectedLocation={picked} layers={layers} assets={data.assets} defects={defects} projects={data.projects.filter((project)=>data.layers.some((layer)=>layer.projectId===project.id)||defects.some((defect)=>defect.projectId===project.id))} focus={selected?{lat:selected.lat,lng:selected.lng}:null}/><aside><header><Layers3/><div><b>Operational layers</b><span>Click a row to show or hide</span></div></header>{data.layers.map((layer)=>{const visible=visibleLayers.includes(layer.id);return <button className={`layer-row ${visible?'active':''}`} key={layer.id} aria-pressed={visible} onClick={()=>setVisibleLayers((current)=>visible?current.filter((id)=>id!==layer.id):[...current,layer.id])}><i style={{background:layer.style.color}}/><span><b>{layer.name}</b><small>{layer.source} · v{layer.version} · {layer.featureCollection.features.length} features</small></span>{visible?<Eye size={16}/>:<EyeOff size={16}/>}<Badge tone={toneFor(layer.status)}>{layer.status}</Badge></button>})}<header><MapPinned/><div><b>Defects on map</b><span>Select to focus location</span></div></header><div className="mapped-defects">{defects.map((defect)=><button key={defect.id} className={selected?.id===defect.id?'active':''} onClick={()=>{setSelected(defect);setPicked(null);}}><span className={`severity-dot ${defect.severity.toLowerCase()}`}/><div><b>{defect.id} · {defect.title}</b><small>{defect.location}</small></div><Badge tone={toneFor(defect.status)}>{defect.status}</Badge></button>)}</div></aside></div>
    {picked&&<Card className="map-selection"><div><span className="selection-pin medium"><Crosshair/></span><div><small>Map-selected point · {picked.addressSource}</small><h2>{picked.address}</h2><p>Use this inspection tool to identify any point on the operational map.</p></div></div><dl><div><dt>Coordinates</dt><dd>{picked.lat.toFixed(6)}, {picked.lng.toFixed(6)}</dd></div><div><dt>Visible layers</dt><dd>{visibleLayers.length} of {data.layers.length}</dd></div><div><dt>Nearby defects</dt><dd>{defects.filter((d)=>Math.abs(d.lat-picked.lat)<0.01&&Math.abs(d.lng-picked.lng)<0.01).length}</dd></div></dl></Card>}
    {selected&&<Card className="map-selection"><div><span className={`selection-pin ${selected.severity.toLowerCase()}`}><MapPinned/></span><div><small>{selected.id} · {selected.source}</small><h2>{selected.title}</h2><p>{selected.description}</p></div></div><dl><div><dt>Coordinates</dt><dd>{selected.lat.toFixed(6)}, {selected.lng.toFixed(6)}</dd></div><div><dt>Geofence</dt><dd>{selected.geofence?<><CheckCircle2/> {selected.geofence.within?'Within':'Outside'} {selected.geofence.sourceType.toLowerCase()} scope · {selected.geofence.distanceMeters} m</>:'No linked scope'}</dd></div><div><dt>Underlying asset</dt><dd>{data.assets.find((asset)=>asset.id===selected.assetId)?.name||'Unlinked'}</dd></div><div><dt>Network layer</dt><dd>{data.layers.find((layer)=>layer.id===data.assets.find((asset)=>asset.id===selected.assetId)?.layerId)?.name||'No published layer'}</dd></div></dl></Card>}
  </div>;
}
