import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Building2, Check, ChevronRight, CirclePlus, FolderKanban, PackageSearch, Plus, Settings2, UserPlus, Users } from 'lucide-react';
import type { Asset, GisOverview, Project, Role, Session, Tenant, User } from '../../shared/types';
import { ALL_MODULES, ROLE_LABELS } from '../../shared/types';
import { patch, post } from '../api';
import { Badge, Button, Card, Field, Loading, Modal, SectionHeader } from '../components/UI';
import MapplsMap from '../components/MapplsMap';
import { ErrorBanner, formatDate, toneFor, useData } from './shared';

export function TenantsPage() {
  const {data,setData,loading,error}=useData<Tenant[]>('/api/tenants',[]);
  const [busy,setBusy]=useState('');
  async function toggle(tenant:Tenant){setBusy(tenant.id);try{const updated=await patch<Tenant>(`/api/tenants/${tenant.id}`,{status:tenant.status==='Live'?'Inactive':'Live'});setData(data.map((t)=>t.id===updated.id?updated:t));}finally{setBusy('');}}
  if(loading)return <Loading label="Loading tenant estate"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow="TENANT ADMINISTRATOR · DIGITAL INDIA" title="Tenant Management" description="Provision, configure and oversee every tenant on the platform."/>
    <div className="kpi-grid"><Card className="kpi-card"><strong>{data.length}</strong><span>Total tenants</span></Card><Card className="kpi-card"><strong>{data.filter((t)=>t.status==='Live').length}</strong><span>Live tenants</span></Card><Card className="kpi-card"><strong>{data.reduce((n,t)=>n+t.modules.length,0)}</strong><span>Modules enabled</span></Card><Card className="kpi-card"><strong>{data.filter((t)=>t.status==='Provisioning').length}</strong><span>Pending provisioning</span></Card></div>
    <Card><div className="card-heading"><div><Building2 size={19}/><h2>All tenants</h2></div></div><div className="table-wrap"><table><thead><tr><th>Tenant</th><th>Asset types</th><th>Modules</th><th>Users</th><th>Status</th><th/></tr></thead><tbody>{data.map((t)=><tr key={t.id}><td><div className="entity-name"><span style={{background:t.primaryColor}}>{t.shortName.slice(0,2)}</span><div><b>{t.shortName}</b><small>{t.name}</small></div></div></td><td>{t.assetTypes.map((a)=>a.name).join(', ')||'—'}</td><td>{t.modules.length} / {ALL_MODULES.length}</td><td>{t.users.toLocaleString('en-IN')}</td><td><Badge tone={toneFor(t.status)}>{t.status}</Badge></td><td><Button variant="ghost" disabled={busy===t.id||t.status==='Requested'} onClick={()=>toggle(t)}>{t.status==='Live'?'Deactivate':'Activate'}</Button></td></tr>)}</tbody></table></div></Card>
  </div>;
}

const initialTenant={name:'',shortName:'',type:'Urban Local Body',hierarchy:'HQ → Zones → Divisions → Offices',modules:['Access & Onboarding','Project Management','Asset Management','Inspections','Defect Management','Citizen App','Dashboards & Reports'],assetTypes:[{name:'Streetlight',attributes:['Pole type','Wattage'],checklist:['Luminaire condition','Pole stability','Wiring safety']}],slas:{Critical:24,High:72,Medium:168,Low:360},dataMigration:false};

export function OnboardingPage() {
  const [step,setStep]=useState(0);const [form,setForm]=useState(initialTenant);const [saving,setSaving]=useState(false);const [created,setCreated]=useState<Tenant|null>(null);const [error,setError]=useState('');
  const steps=['Organisation','Asset Types','Modules','SLAs','Review'];
  function addAsset(){setForm({...form,assetTypes:[...form.assetTypes,{name:'New Asset Type',attributes:['Attribute'],checklist:['Inspection item']}]});}
  async function submit(){setSaving(true);setError('');try{setCreated(await post<Tenant>('/api/tenants',form));}catch(e){setError(e instanceof Error?e.message:'Unable to provision tenant');}finally{setSaving(false);}}
  if(created)return <div className="success-screen"><span><Check/></span><h1>{created.shortName} provisioning started</h1><p>{created.name} has been created with {created.assetTypes.length} asset types and {created.modules.length} enabled modules. The first Super Admin can now be assigned.</p><Button onClick={()=>{setCreated(null);setStep(0);setForm(initialTenant);}}>Provision another tenant</Button></div>;
  return <div className="page-stack"><SectionHeader eyebrow="TENANT ADMINISTRATOR · DIGITAL INDIA" title="Provision New Tenant" description="Configure the organisation, asset vocabulary, enabled modules and tenant-level SLAs."/>
    <Card className="wizard-card"><div className="wizard-steps">{steps.map((label,i)=><button key={label} className={i===step?'active':i<step?'done':''} onClick={()=>setStep(i)}><i>{i<step?<Check size={15}/>:i+1}</i><span>{label}</span>{i<steps.length-1&&<b/>}</button>)}</div>
      <div className="wizard-body"><ErrorBanner message={error}/>{step===0&&<div><h2>Step 1 · Organisation</h2><p>Tenant identity, organisational hierarchy and platform-role mapping.</p><div className="form-grid"><Field label="Tenant name"><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} placeholder="e.g. Sunrise Municipal Corporation"/></Field><Field label="Short name"><input value={form.shortName} onChange={(e)=>setForm({...form,shortName:e.target.value.toUpperCase()})} placeholder="SMC"/></Field><Field label="Organisation type"><select value={form.type} onChange={(e)=>setForm({...form,type:e.target.value})}><option>Urban Local Body</option><option>National Highway Authority</option><option>Public Works Department</option><option>Water & Sanitation Utility</option></select></Field><Field label="Organisation hierarchy"><input value={form.hierarchy} onChange={(e)=>setForm({...form,hierarchy:e.target.value})}/></Field></div><div className="role-map">{(['authority','maker','checker','citizen'] as Role[]).map((r)=><div key={r}><b>{ROLE_LABELS[r]}</b><span>{r==='authority'?'Tenant Super Admin and governing officials':r==='maker'?'Field staff executing the work':r==='checker'?'Supervisors validating the work':'Public users with no organisation affiliation'}</span></div>)}</div></div>}
      {step===1&&<div><h2>Step 2 · Configurable asset types</h2><p>Each asset type owns its attributes and inspection checklist; nothing is hardcoded to roads.</p><div className="asset-type-editor">{form.assetTypes.map((asset,index)=><Card key={index}><Field label="Asset type name"><input value={asset.name} onChange={(e)=>{const items=[...form.assetTypes];items[index]={...asset,name:e.target.value};setForm({...form,assetTypes:items});}}/></Field><Field label="Attributes · comma separated"><input value={asset.attributes.join(', ')} onChange={(e)=>{const items=[...form.assetTypes];items[index]={...asset,attributes:e.target.value.split(',').map((x)=>x.trim()).filter(Boolean)};setForm({...form,assetTypes:items});}}/></Field><Field label="Inspection checklist · comma separated"><textarea value={asset.checklist.join(', ')} onChange={(e)=>{const items=[...form.assetTypes];items[index]={...asset,checklist:e.target.value.split(',').map((x)=>x.trim()).filter(Boolean)};setForm({...form,assetTypes:items});}}/></Field></Card>)}</div><Button variant="secondary" onClick={addAsset} icon={<Plus size={17}/>}>Add asset type</Button></div>}
      {step===2&&<div><h2>Step 3 · Enabled modules</h2><p>Access & Onboarding and Project Management are mandatory. Every other capability is optional per tenant.</p><div className="module-toggle-grid">{ALL_MODULES.map((module)=>{const mandatory=['Access & Onboarding','Project Management'].includes(module);const enabled=form.modules.includes(module);return <button key={module} className={enabled?'enabled':''} disabled={mandatory} onClick={()=>setForm({...form,modules:enabled?form.modules.filter((m)=>m!==module):[...form.modules,module]})}><span>{enabled?<Check/>:<Plus/>}</span><b>{module}</b><small>{mandatory?'Mandatory':enabled?'Enabled':'Disabled'}</small></button>})}</div></div>}
      {step===3&&<div><h2>Step 4 · Tenant SLAs</h2><p>Resolution thresholds are configured per tenant and drive automated escalation to Authority Users.</p><div className="sla-grid">{[['Critical','24 hours'],['High','3 days'],['Medium','7 days'],['Low','15 days']].map(([severity,value])=><div key={severity}><Badge tone={toneFor(severity)}>{severity}</Badge><Field label="Defect resolution"><input value={value} readOnly/></Field><Field label="Helpdesk response"><input value={severity==='Critical'?'4 hours':severity==='High'?'1 day':severity==='Medium'?'3 days':'7 days'} readOnly/></Field></div>)}</div><label className="check-row"><input type="checkbox" checked={form.dataMigration} onChange={(e)=>setForm({...form,dataMigration:e.target.checked})}/><span><b>Legacy data migration required</b><small>Flag this tenant for migration planning during implementation.</small></span></label></div>}
      {step===4&&<div><h2>Step 5 · Review & provision</h2><p>Confirm the platform configuration before creating the tenant.</p><div className="review-grid"><div><span>Organisation</span><b>{form.name||'Not entered'}</b><small>{form.shortName||'—'} · {form.type}</small></div><div><span>Hierarchy</span><b>{form.hierarchy}</b></div><div><span>Asset types</span><b>{form.assetTypes.map((a)=>a.name).join(', ')}</b><small>{form.assetTypes.reduce((n,a)=>n+a.attributes.length,0)} configured attributes</small></div><div><span>Modules</span><b>{form.modules.length} of {ALL_MODULES.length} enabled</b></div><div><span>Data migration</span><b>{form.dataMigration?'Required':'Not required'}</b></div></div></div>}
      </div><footer className="wizard-footer"><Button variant="secondary" onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0}><ArrowLeft size={17}/> Back</Button>{step<4?<Button onClick={()=>setStep(step+1)} disabled={step===0&&(!form.name||!form.shortName)}>Continue <ArrowRight size={17}/></Button>:<Button onClick={submit} disabled={saving}>{saving?'Provisioning…':'Provision tenant'} <ChevronRight size={17}/></Button>}</footer>
    </Card></div>;
}

export function UsersPage({session}:{session:Session}) {
  const {data,setData,loading,error}=useData<User[]>('/api/users',[]);const [modal,setModal]=useState(false);const [form,setForm]=useState({name:'',email:'',mobile:'+91 ',role:'authority' as Role,designation:'HQ Official'});const [saving,setSaving]=useState(false);
  async function save(){setSaving(true);try{const user=await post<User>('/api/users',form);setData([user,...data]);setModal(false);setForm({name:'',email:'',mobile:'+91 ',role:'authority',designation:'HQ Official'});}finally{setSaving(false);}}
  if(loading)return <Loading label="Loading tenant users"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow={session.tenant?.shortName} title="User Management & Invites" description="Authority Users are invited to the tenant; External Makers and Checkers are verified and assigned at project level." action={<Button onClick={()=>setModal(true)} icon={<UserPlus size={17}/>}>Invite user</Button>}/><Card><div className="card-heading"><div><Users size={19}/><h2>Tenant user directory</h2></div><span>{data.length} active identities</span></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Type</th><th>Designation</th><th>Contact</th><th>Status</th></tr></thead><tbody>{data.map((u)=><tr key={u.id}><td><div className="entity-name"><span>{u.name.split(' ').map((n)=>n[0]).join('').slice(0,2)}</span><b>{u.name}</b></div></td><td><Badge tone={u.role==='authority'?'info':u.role==='maker'?'warning':u.role==='checker'?'success':'neutral'}>{ROLE_LABELS[u.role]}</Badge></td><td>{u.designation}</td><td>{u.email||u.mobile}</td><td><Badge tone={u.active?'success':'neutral'}>{u.active?'Active':'Inactive'}</Badge></td></tr>)}</tbody></table></div></Card>{modal&&<Modal title="Invite a tenant user" onClose={()=>setModal(false)} footer={<><Button variant="secondary" onClick={()=>setModal(false)}>Cancel</Button><Button onClick={save} disabled={saving||!form.name}>{saving?'Sending…':'Send invite'}</Button></>}><div className="form-grid"><Field label="Full name"><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} placeholder="e.g. Anjali Menon"/></Field><Field label="Email"><input type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} placeholder="name@agency.gov.in"/></Field><Field label="Mobile"><input value={form.mobile} onChange={(e)=>setForm({...form,mobile:e.target.value})}/></Field><Field label="User type"><select value={form.role} onChange={(e)=>setForm({...form,role:e.target.value as Role})}><option value="authority">Authority</option><option value="maker">Maker</option><option value="checker">Checker</option></select></Field><Field label="Designation"><input value={form.designation} onChange={(e)=>setForm({...form,designation:e.target.value})}/></Field></div></Modal>}</div>;
}

export function ProjectsPage({session}:{session:Session}) {
  const {data,setData,loading,error}=useData<Project[]>('/api/projects',[]);const [modal,setModal]=useState(false);const [form,setForm]=useState({code:'',name:'',location:'',assetType:session.tenant?.assetTypes[0]?.name||'Infrastructure Asset',makerIds:[] as string[],checkerIds:[] as string[]});
  async function save(){const project=await post<Project>('/api/projects',form);setData([project,...data]);setModal(false);}
  if(loading)return <Loading label="Loading projects"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow={session.tenant?.shortName} title="Project Management" description="Create projects, map Maker and Checker stakeholders, monitor timelines and keep project-level accountability." action={session.user.role==='authority'?<Button onClick={()=>setModal(true)} icon={<CirclePlus size={17}/>}>Create project</Button>:undefined}/><div className="project-grid">{data.map((p)=><Card className="project-card" key={p.id}><header><span><FolderKanban/></span><Badge tone={toneFor(p.status)}>{p.status}</Badge></header><small>{p.code}</small><h2>{p.name}</h2><p>{p.location}</p><div className="progress-label"><span>Overall progress</span><b>{p.progress}%</b></div><div className="progress"><i style={{width:`${p.progress}%`}}/></div><footer><span><Users size={15}/> {p.makerIds.length} Maker · {p.checkerIds.length} Checker</span><span>{p.assetType}</span></footer></Card>)}</div>{modal&&<Modal title="Create project" onClose={()=>setModal(false)} footer={<><Button variant="secondary" onClick={()=>setModal(false)}>Cancel</Button><Button onClick={save} disabled={!form.code||!form.name}>Create project</Button></>}><div className="form-grid"><Field label="Project ID"><input value={form.code} onChange={(e)=>setForm({...form,code:e.target.value})} placeholder="PWD/2026/021"/></Field><Field label="Project name"><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></Field><Field label="Location"><input value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></Field><Field label="Primary asset type"><select value={form.assetType} onChange={(e)=>setForm({...form,assetType:e.target.value})}>{session.tenant?.assetTypes.map((a)=><option key={a.id}>{a.name}</option>)}</select></Field></div><p className="form-note">Maker and Checker assignments can be added after project creation. Their agency relationship remains project-scoped.</p></Modal>}</div>;
}

export function AssetsPage({session}:{session:Session}) {
  const {data,setData,loading,error}=useData<Asset[]>('/api/assets',[]);const {data:projects}=useData<Project[]>('/api/projects',[]);const {data:gis}=useData<GisOverview>('/api/gis/overview',{configured:false,provider:'Mappls',layers:[],assets:[],defects:[],projects:[]});const [modal,setModal]=useState(false);const firstProject=projects[0];const [form,setForm]=useState({projectId:'',type:session.tenant?.assetTypes[0]?.name||'',name:'',location:'',condition:'Good' as Asset['condition'],attributes:{} as Record<string,string>});
  const types=useMemo(()=>session.tenant?.assetTypes||[],[session.tenant]);
  async function save(){const asset=await post<Asset>('/api/assets',{...form,projectId:form.projectId||firstProject?.id});setData([asset,...data]);setModal(false);}
  if(loading)return <Loading label="Loading asset register"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow={session.tenant?.shortName} title="Asset Management" description="A tenant-configurable infrastructure register with asset-specific attributes, inspection templates, geometry and published GIS-layer context." action={session.user.role==='authority'?<Button onClick={()=>setModal(true)} icon={<Plus size={17}/>}>Register asset</Button>:undefined}/><MapplsMap layers={gis.layers} assets={data} defects={gis.defects} projects={projects}/><div className="asset-grid">{data.map((a)=><Card className="asset-card" key={a.id}><header><span><PackageSearch/></span><Badge tone={toneFor(a.condition)}>{a.condition}</Badge></header><small>{a.type}</small><h2>{a.name}</h2><p>{a.location}</p><dl>{Object.entries(a.attributes).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="asset-spatial"><Badge tone="info">{a.geometry.type}</Badge><span>{gis.layers.find((layer)=>layer.id===a.layerId)?.name||'Project geometry'}</span></div><footer>Last inspected · {formatDate(a.lastInspected)}</footer></Card>)}</div>{modal&&<Modal title="Register an asset" onClose={()=>setModal(false)} footer={<><Button variant="secondary" onClick={()=>setModal(false)}>Cancel</Button><Button onClick={save} disabled={!form.name}>Register asset</Button></>}><p className="form-note">Manual registration uses the selected project centre as the initial point geometry. Bulk KML/SHP ingestion remains specification-gated because attribute mapping, CRS, validation and network-version rules are not defined in PRD v1.2.</p><div className="form-grid"><Field label="Project"><select value={form.projectId} onChange={(e)=>setForm({...form,projectId:e.target.value})}><option value="">Select project</option>{projects.map((p)=><option value={p.id} key={p.id}>{p.code} · {p.name}</option>)}</select></Field><Field label="Asset type"><select value={form.type} onChange={(e)=>setForm({...form,type:e.target.value,attributes:{}})}>{types.map((t)=><option key={t.id}>{t.name}</option>)}</select></Field><Field label="Asset name"><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></Field><Field label="Location"><input value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></Field><Field label="Condition"><select value={form.condition} onChange={(e)=>setForm({...form,condition:e.target.value as Asset['condition']})}><option>Good</option><option>Fair</option><option>Attention</option><option>Critical</option></select></Field></div><h3 className="subform-title">Configured attributes</h3><div className="form-grid">{types.find((t)=>t.name===form.type)?.attributes.map((attribute)=><Field label={attribute} key={attribute}><input value={form.attributes[attribute]||''} onChange={(e)=>setForm({...form,attributes:{...form.attributes,[attribute]:e.target.value}})}/></Field>)}</div></Modal>}</div>;
}
