import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, Camera, Check, CheckCircle2, ClipboardCheck, CloudOff, CreditCard, Crosshair, FileCheck2, HelpCircle, LocateFixed, MapPin, MessageCircleQuestion, Pause, Play, Plus, RefreshCw, ShieldCheck, Smartphone, ThumbsUp, TicketCheck, Upload, UserCheck, Wrench, X } from 'lucide-react';
import type { Activity, Asset, AttendanceRecord, Defect, GisLayer, GisOverview, HelpdeskTicket, Inspection, MediaEvidence, Payment, Project, Session, User } from '../../shared/types';
import { patch, post, uploadEvidence } from '../api';
import { Badge, Button, Card, Field, Loading, Modal, SectionHeader } from '../components/UI';
import MapplsMap from '../components/MapplsMap';
import { captureDeviceLocation, enrichLocation, type LocatedPoint } from '../location';
import { ErrorBanner, formatDate, formatMoney, toneFor, useData } from './shared';

function distanceMeters(a:{lat:number;lng:number},b:{lat:number;lng:number}) {
  const toRad=(value:number)=>value*Math.PI/180;const dLat=toRad(b.lat-a.lat);const dLng=toRad(b.lng-a.lng);const lat1=toRad(a.lat);const lat2=toRad(b.lat);
  return 12_742_000*Math.asin(Math.sqrt(Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2));
}

function EvidenceCapture({location,evidence,setEvidence,label}:{location:LocatedPoint;evidence:MediaEvidence[];setEvidence:(items:MediaEvidence[])=>void;label:string}) {
  const [uploading,setUploading]=useState(false);const [error,setError]=useState('');
  async function choose(files:FileList|null){if(!files?.length)return;setUploading(true);setError('');try{const selected=Array.from(files).slice(0,Math.max(0,3-evidence.length));const uploaded:MediaEvidence[]=[];for(const file of selected){if(file.size>8*1024*1024)throw new Error(`${file.name} exceeds the 8 MB prototype limit.`);if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))throw new Error(`${file.name} is not a supported photo or video.`);uploaded.push(await uploadEvidence(file,location));}setEvidence([...evidence,...uploaded]);}catch(e){setError(e instanceof Error?e.message:'Evidence upload failed.');}finally{setUploading(false);}}
  return <div className="evidence-capture"><label className="upload-box interactive"><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,video/mp4,video/quicktime,video/webm" capture="environment" multiple onChange={(event)=>void choose(event.target.files)} disabled={uploading||evidence.length>=3}/><Upload/><b>{uploading?'Uploading geo-tagged evidence…':evidence.length?`${evidence.length} evidence file${evidence.length===1?'':'s'} captured`:label}</b><small>Photo or video · maximum 8 MB each · coordinates and accuracy stored on the server</small></label>{error&&<p className="form-error">{error}</p>}{evidence.length>0&&<div className="evidence-list">{evidence.map((item)=><span key={item.id}><Camera/><b>{item.originalName}</b><small>{(item.size/1024).toFixed(0)} KB · {item.lat.toFixed(5)}, {item.lng.toFixed(5)}</small><button type="button" onClick={()=>setEvidence(evidence.filter((entry)=>entry.id!==item.id))} aria-label={`Remove ${item.originalName}`}><X/></button></span>)}</div>}</div>;
}

export function AttendancePage({session}:{session:Session}) {
  const {data,setData,loading,error}=useData<AttendanceRecord[]>('/api/attendance',[]);const {data:projects}=useData<Project[]>('/api/projects',[]);const {data:users}=useData<User[]>('/api/users',[]);const {data:gis}=useData<GisOverview>('/api/gis/overview',{configured:false,provider:'Mappls',layers:[],assets:[],defects:[],projects:[]});const [projectId,setProjectId]=useState('');const [marking,setMarking]=useState(false);const [locating,setLocating]=useState(false);const isMaker=session.user.role==='maker';
  const selectedProject=projects.find((project)=>project.id===(projectId||projects[0]?.id));
  const fallback:LocatedPoint=session.tenant?.id==='tenant-nhai'?{lat:23.1462,lng:79.9341,accuracyMeters:8,source:'Demo location',address:'NH 44, Jabalpur, Madhya Pradesh',addressSource:'Demo data'}:{lat:28.6139,lng:77.2090,accuracyMeters:8,source:'Demo location',address:'Kartavya Path, New Delhi',addressSource:'Demo data'};
  const [location,setLocation]=useState<LocatedPoint>(fallback);
  const distance=selectedProject?Math.round(distanceMeters(location,selectedProject.center)):null;const inside=distance!==null&&selectedProject?distance<=selectedProject.geofenceRadiusMeters:false;
  async function locate(){setLocating(true);setLocation(await captureDeviceLocation(fallback));setLocating(false);}
  async function mark(){if(!selectedProject)return;setMarking(true);try{const record=await post<AttendanceRecord>('/api/attendance',{projectId:selectedProject.id,lat:location.lat,lng:location.lng,accuracyMeters:location.accuracyMeters,offline:false});setData([record,...data.filter((a)=>a.id!==record.id)]);}finally{setMarking(false);}}
  if(loading)return <Loading label="Loading attendance records"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow={isMaker?'MOBILE FIELD ACTION':'WEB OVERSIGHT'} title={isMaker?'Mark Attendance':'Attendance Oversight'} description={isMaker?'Geo-fenced attendance is mobile-only and available only to Makers.':'Checker and Authority users can view attendance status across assigned projects.'}/>
    {isMaker&&<div className="mobile-action-layout"><div className="phone-frame"><div className="phone-status">9:41 <span>● ● ◼</span></div><div className="phone-content"><span className={`phone-icon ${inside?'':'outside'}`}><LocateFixed/></span><small>{inside?'YOU ARE WITHIN THE PROJECT GEOFENCE':'LOCATION IS OUTSIDE THE PROJECT GEOFENCE'}</small><h2>{inside?'Ready to mark attendance':'Attendance will be flagged'}</h2><p>{location.source} · ±{location.accuracyMeters} metres<br/><b>{location.address}</b><br/><small>{location.addressSource}</small><br/>{distance===null?'Select a project':`${distance} m from project centre`}</p><Field label="Project"><select value={projectId} onChange={(e)=>setProjectId(e.target.value)}>{projects.map((p)=><option key={p.id} value={p.id}>{p.code}</option>)}</select></Field><Button variant="secondary" onClick={locate} disabled={locating} icon={<Crosshair/>}>{locating?'Capturing GPS & address…':'Use my current location'}</Button><button className="attendance-button" onClick={mark} disabled={marking||!selectedProject}><MapPin/>{marking?'Verifying on server…':'Mark attendance now'}</button><span className="sync-state"><CloudOff/> Server computes the geofence result; the client cannot override it</span></div></div><Card className="mobile-context map-context"><Smartphone/><h2>Server-verified geofence</h2><p>The project centre and radius are tenant data. Device coordinates are submitted with accuracy, and the API calculates distance before recording attendance.</p><MapplsMap compact layers={gis.layers.filter((layer)=>layer.projectId===selectedProject?.id)} projects={selectedProject?[selectedProject]:[]} focus={location}/><div className="geofence-summary"><b>{selectedProject?.geofenceRadiusMeters||250} m radius</b><span>{distance??'—'} m measured distance</span><Badge tone={inside?'success':'danger'}>{inside?'Within scope':'Outside scope'}</Badge></div></Card></div>}
    <Card><div className="card-heading"><div><UserCheck size={19}/><h2>{isMaker?'My attendance history':'Team attendance'}</h2></div><Badge tone="info">Geo-verified</Badge></div><div className="table-wrap"><table><thead><tr><th>Maker</th><th>Date</th><th>Project</th><th>Hours</th><th>Location</th><th>Status</th></tr></thead><tbody>{data.map((a)=>{const user=users.find((u)=>u.id===a.makerId);return <tr key={a.id}><td><b>{user?.name||a.makerId}</b></td><td>{formatDate(a.date)}</td><td>{projects.find((p)=>p.id===a.projectId)?.code}</td><td>{a.checkIn} – {a.checkOut||'In progress'}</td><td>{a.lat.toFixed(4)}, {a.lng.toFixed(4)}</td><td><Badge tone={toneFor(a.status)}>{a.status}</Badge></td></tr>})}</tbody></table></div></Card></div>;
}

export function InspectionsPage({session}:{session:Session}) {
  const {data,setData,loading,error}=useData<Inspection[]>('/api/inspections',[]);const {data:projects}=useData<Project[]>('/api/projects',[]);const {data:assets}=useData<Asset[]>('/api/assets',[]);const {data:users}=useData<User[]>('/api/users',[]);const [modal,setModal]=useState(false);const [typeFilter,setTypeFilter]=useState<'Joint'|'Requested'>('Joint');const [deviceView,setDeviceView]=useState<'web'|'mobile'>('web');const [form,setForm]=useState({projectId:'',assetId:'',type:'Joint' as Inspection['type'],makerId:'',checkerId:'',scheduledAt:new Date(Date.now()+86_400_000).toISOString().slice(0,16),checklist:['Structural condition','Electrical safety','Fire safety']});
  async function action(item:Inspection,status:Inspection['status']){const updated=await patch<Inspection>(`/api/inspections/${item.id}`,{status});setData(data.map((i)=>i.id===updated.id?updated:i));}
  async function setChecklist(item:Inspection,index:number,status:'Pass'|'Flag'){const note=status==='Flag'?(window.prompt('Describe the defect or follow-up required:',item.checklist[index].note||'Requires defect follow-up')||'Requires defect follow-up'):undefined;const checklist=item.checklist.map((entry,i)=>i===index?{...entry,status,note}:entry);const updated=await patch<Inspection>(`/api/inspections/${item.id}`,{checklist});setData(data.map((i)=>i.id===updated.id?updated:i));}
  async function create(){const item=await post<Inspection>('/api/inspections',{...form,scheduledAt:new Date(form.scheduledAt).toISOString()});setData([item,...data]);setModal(false);}
  if(loading)return <Loading label="Loading inspection programme"/>;
  const canSchedule=session.user.role!=='citizen';
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow="JOINT + REQUEST FOR INSPECTION" title="Inspection Management" description="Schedule and accept on web; conduct on mobile using the checklist configured for the selected asset type." action={canSchedule?<Button onClick={()=>setModal(true)} icon={<Plus size={17}/>}>Schedule inspection</Button>:undefined}/>
    <div className="split-tabs"><button className={typeFilter==='Joint'?'active':''} onClick={()=>setTypeFilter('Joint')}>Joint Inspection</button><button className={typeFilter==='Requested'?'active':''} onClick={()=>setTypeFilter('Requested')}>Request for Inspection</button><span/><button className={deviceView==='web'?'active':''} onClick={()=>setDeviceView('web')}>Web overview</button><button className={deviceView==='mobile'?'device-active':''} onClick={()=>setDeviceView('mobile')}><Smartphone size={15}/> Mobile field action</button></div>
    {deviceView==='mobile'&&!['maker','checker'].includes(session.user.role)&&<p className="form-note"><Smartphone size={16}/> Field execution is restricted to assigned Maker and Checker users; this Authority view remains read-only.</p>}
    <div className="inspection-grid">{data.filter((item)=>item.type===typeFilter).map((i)=><Card className="inspection-card" key={i.id}><header><div><span className="list-icon"><ClipboardCheck/></span><div><small>{i.id} · {i.type}</small><h2>{projects.find((p)=>p.id===i.projectId)?.name||i.assetId}</h2></div></div><Badge tone={toneFor(i.status)}>{i.status}</Badge></header><p><MapPin size={15}/> {projects.find((p)=>p.id===i.projectId)?.location}</p><div className="checklist-preview">{i.checklist.map((c,index)=><div key={c.item}><span className={c.status.toLowerCase()}>{c.status==='Pass'?<Check/>:c.status==='Flag'?<AlertTriangle/>:<span/>}</span><b>{c.item}</b>{c.note&&<small>{c.note}</small>}{deviceView==='mobile'&&i.status==='In Progress'&&['maker','checker'].includes(session.user.role)&&<aside><button onClick={()=>setChecklist(i,index,'Pass')} className={c.status==='Pass'?'active pass':''}>Pass</button><button onClick={()=>setChecklist(i,index,'Flag')} className={c.status==='Flag'?'active flag':''}>Flag</button></aside>}</div>)}</div><footer><span><CloudOff size={15}/> {i.offlineState}</span><div>{i.status==='Scheduled'&&session.user.role==='checker'&&<><Button variant="ghost" onClick={()=>action(i,'Rejected')}>Reject</Button>{i.type==='Requested'&&<Button variant="ghost" onClick={()=>action(i,'Not Ready')}>Not ready</Button>}<Button variant="secondary" onClick={()=>action(i,'Accepted')}>Accept</Button></>}{deviceView==='mobile'&&['Accepted','Paused'].includes(i.status)&&['maker','checker'].includes(session.user.role)&&<Button onClick={()=>action(i,'In Progress')} icon={<Play size={15}/>}>{i.status==='Paused'?'Resume':'Start on mobile'}</Button>}{deviceView==='mobile'&&i.status==='In Progress'&&['maker','checker'].includes(session.user.role)&&<><Button variant="secondary" onClick={()=>action(i,'Paused')} icon={<Pause size={15}/>}>Pause</Button><Button onClick={()=>action(i,'Completed')} disabled={i.checklist.some((item)=>item.status==='Pending')} icon={<Check size={15}/>}>Complete</Button></>}</div></footer></Card>)}</div>
    {modal&&<Modal title="Schedule an inspection" onClose={()=>setModal(false)} footer={<><Button variant="secondary" onClick={()=>setModal(false)}>Cancel</Button><Button onClick={create} disabled={!form.projectId||!form.assetId||!form.makerId||!form.checkerId}>Schedule</Button></>}><div className="form-grid"><Field label="Project"><select value={form.projectId} onChange={(e)=>{const projectId=e.target.value;setForm({...form,projectId,assetId:assets.find((asset)=>asset.projectId===projectId)?.id||''});}}><option value="">Select project</option>{projects.map((p)=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></Field><Field label="Asset"><select value={form.assetId} onChange={(e)=>setForm({...form,assetId:e.target.value})}><option value="">Select asset</option>{assets.filter((asset)=>asset.projectId===form.projectId).map((asset)=><option key={asset.id} value={asset.id}>{asset.name}</option>)}</select></Field><Field label="Inspection type"><select value={form.type} onChange={(e)=>setForm({...form,type:e.target.value as Inspection['type']})}><option>Joint</option><option>Requested</option></select></Field><Field label="Maker"><select value={form.makerId} onChange={(e)=>setForm({...form,makerId:e.target.value})}><option value="">Select Maker</option>{users.filter((user)=>user.role==='maker'&&user.active).map((user)=><option key={user.id} value={user.id}>{user.name}</option>)}</select></Field><Field label="Checker"><select value={form.checkerId} onChange={(e)=>setForm({...form,checkerId:e.target.value})}><option value="">Select Checker</option>{users.filter((user)=>user.role==='checker'&&user.active).map((user)=><option key={user.id} value={user.id}>{user.name}</option>)}</select></Field><Field label="Schedule"><input type="datetime-local" value={form.scheduledAt} onChange={(e)=>setForm({...form,scheduledAt:e.target.value})}/></Field><Field label="Checklist items"><textarea value={form.checklist.join(', ')} onChange={(e)=>setForm({...form,checklist:e.target.value.split(',').map((x)=>x.trim()).filter(Boolean)})}/></Field></div></Modal>}
  </div>;
}

export function DefectsPage({session}:{session:Session}) {
  const {data,setData,loading,error}=useData<Defect[]>('/api/defects',[]);const {data:gis}=useData<GisOverview>('/api/gis/overview',{configured:false,provider:'Mappls',layers:[],assets:[],defects:[],projects:[]});const {data:activities}=useData<Activity[]>('/api/activities',[]);const [modal,setModal]=useState(false);const [history,setHistory]=useState<Defect|null>(null);const [atr,setAtr]=useState<Defect|null>(null);const [atrText,setAtrText]=useState('');const [atrEvidence,setAtrEvidence]=useState<MediaEvidence[]>([]);const [view,setView]=useState<'list'|'map'>('list');const [atrLocation,setAtrLocation]=useState<LocatedPoint>({lat:28.6139,lng:77.2090,accuracyMeters:8,source:'Demo location',address:'Kartavya Path, New Delhi',addressSource:'Demo data'});const [atrLocating,setAtrLocating]=useState(false);
  const role=session.user.role;const queue=data.filter((d)=>d.checkerValidation==='Pending');const defects=role==='checker'?[...queue,...data.filter((d)=>d.checkerValidation!=='Pending')]:data;
  async function validate(d:Defect,decision:'approve'|'reject'){const updated=await post<Defect>(`/api/defects/${d.id}/validate`,{decision});setData(data.map((x)=>x.id===updated.id?updated:x));}
  async function start(d:Defect){const updated=await post<Defect>(`/api/defects/${d.id}/start`,{});setData(data.map((x)=>x.id===updated.id?updated:x));}
  async function locateAtr(){if(!atr)return;setAtrLocating(true);setAtrLocation(await captureDeviceLocation({lat:atr.lat,lng:atr.lng,accuracyMeters:10,source:'Demo location',address:atr.location,addressSource:'Stored defect address'}));setAtrLocating(false);}
  async function selectAtr(point:{lat:number;lng:number}){setAtrLocation(await enrichLocation({...point,accuracyMeters:0,source:'Map selection' as const}));}
  async function submitAtr(){if(!atr||!atrEvidence.length)return;const updated=await post<Defect>(`/api/defects/${atr.id}/atr`,{summary:atrText,media:atrEvidence.map((item)=>item.id),lat:atrLocation.lat,lng:atrLocation.lng,accuracyMeters:atrLocation.accuracyMeters});setData(data.map((d)=>d.id===updated.id?updated:d));setAtr(null);setAtrText('');setAtrEvidence([]);}
  async function verify(d:Defect,decision:'verify'|'rework'){const updated=await post<Defect>(`/api/defects/${d.id}/verify-atr`,{decision,note:decision==='verify'?'Geo-tagged evidence and work outcome verified on site.':'Evidence or rectification requires another field cycle.'});setData(data.map((x)=>x.id===updated.id?updated:x));}
  if(loading)return <Loading label="Loading defect workflow"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow={role==='checker'?'CHECKER VALIDATION + ATR VERIFICATION':'DEFECT LIFECYCLE'} title="Defect Management" description="Citizen submissions are validated before assignment; every repair closes only after Checker verification." action={<Button onClick={()=>setModal(true)} icon={<Plus size={17}/>}>Raise defect</Button>}/>
    {role==='checker'&&queue.length>0&&<div className="attention-banner"><AlertTriangle/><div><b>{queue.length} citizen submission{queue.length>1?'s':''} awaiting validation</b><span>Review duplicates and severity before creating official work items.</span></div></div>}
    <div className="view-switch"><button className={view==='list'?'active':''} onClick={()=>setView('list')}>Defect register</button><button className={view==='map'?'active':''} onClick={()=>setView('map')}><MapPin/> Map with network</button></div>
    {view==='map'&&<MapplsMap layers={gis.layers} assets={gis.assets} defects={defects} projects={gis.projects}/>}
    {view==='list'&&<Card>
      <div className="card-heading"><div><Wrench size={19}/><h2>{role==='checker'?'Validation and closure queue':'Defect register'}</h2></div><span>{defects.length} records</span></div>
      <div className="table-wrap"><table><thead><tr><th>Report</th><th>Issue / location</th><th>Geo verification</th><th>Severity</th><th>Status</th><th>Action</th></tr></thead><tbody>{defects.map((d)=><tr key={d.id}>
        <td><b className="mono">{d.id}</b>{d.duplicateCount>0&&<small>{d.duplicateCount} linked reports</small>}</td>
        <td><b>{d.title}</b><small>{d.location} · {d.source} · {d.media.length} evidence file{d.media.length===1?'':'s'}</small></td>
        <td>{d.geofence?<span className={`geo-proof ${d.geofence.within?'inside':'outside'}`}><LocateFixed/>{d.geofence.within?'Within':'Outside'} {d.geofence.sourceType.toLowerCase()} scope<small>{d.geofence.distanceMeters} m · ±{d.locationAccuracyMeters??'—'} m GPS</small></span>:<span>Unlinked</span>}</td>
        <td><Badge tone={toneFor(d.severity)}>{d.severity}</Badge></td><td><Badge tone={toneFor(d.status)}>{d.status}</Badge></td>
        <td><div className="table-actions">
          {role==='checker'&&d.checkerValidation==='Pending'&&<><Button variant="ghost" onClick={()=>validate(d,'reject')}><X size={15}/> Reject</Button><Button onClick={()=>validate(d,'approve')}><Check size={15}/> Validate</Button></>}
          {role==='maker'&&['Assigned','Reopened'].includes(d.status)&&d.makerId===session.user.id&&<Button variant="secondary" onClick={()=>start(d)}>Start work</Button>}
          {role==='maker'&&d.status==='In Progress'&&d.makerId===session.user.id&&<Button onClick={()=>{setAtr(d);setAtrEvidence([]);setAtrLocation({lat:d.lat,lng:d.lng,accuracyMeters:10,source:'Demo location',address:d.location,addressSource:'Stored defect address'});}}>Submit ATR</Button>}
          {role==='checker'&&d.status==='ATR Submitted'&&<><Button variant="ghost" onClick={()=>verify(d,'rework')}>Return</Button><Button onClick={()=>verify(d,'verify')}>Verify ATR</Button></>}
          <Button variant="ghost" onClick={()=>setHistory(d)}>View history <ArrowRight size={14}/></Button>
        </div></td>
      </tr>)}</tbody></table></div>
    </Card>}
    {modal&&<IssueModal session={session} projects={gis.projects} assets={gis.assets} layers={gis.layers} onClose={()=>setModal(false)} onCreated={(result)=>{setData([result.defect,...data.filter((d)=>d.id!==result.defect.id)]);setModal(false);}}/>}
    {atr&&<Modal title={`Submit Action Taken Report · ${atr.id}`} onClose={()=>setAtr(null)} footer={<><Button variant="secondary" onClick={()=>setAtr(null)}>Cancel</Button><Button onClick={submitAtr} disabled={atrText.length<10||!atrEvidence.length}>Submit for Checker verification</Button></>}>
      <p className="form-note">Capture the completed work at the defect location. The Checker receives the narrative, media, coordinates and accuracy before resolution.</p>
      <MapplsMap compact selectable onLocationSelect={selectAtr} selectedLocation={atrLocation} layers={gis.layers} assets={gis.assets.filter((a)=>a.id===atr.assetId)} defects={[atr]} projects={gis.projects.filter((p)=>p.id===atr.projectId)} focus={atrLocation}/>
      <div className="geo-capture-row"><span><LocateFixed/><b>{atrLocation.source}</b><small>{atrLocation.address}<br/>{atrLocation.lat.toFixed(6)}, {atrLocation.lng.toFixed(6)} · ±{atrLocation.accuracyMeters} m · {atrLocation.addressSource}</small></span><Button variant="secondary" onClick={locateAtr} disabled={atrLocating}>{atrLocating?'Capturing GPS & address…':'Refresh GPS'}</Button></div>
      <Field label="Action taken"><textarea rows={5} value={atrText} onChange={(e)=>setAtrText(e.target.value)} placeholder="Describe work completed, materials used and supporting evidence…"/></Field>
      <EvidenceCapture location={atrLocation} evidence={atrEvidence} setEvidence={setAtrEvidence} label="Capture ATR photo or video"/>
    </Modal>}
    {history&&<Modal title={`Audit history · ${history.id}`} onClose={()=>setHistory(null)} footer={<Button onClick={()=>setHistory(null)}>Done</Button>}><div className="timeline-list">{activities.filter((item)=>item.entityId===history.id).map((item)=><div key={item.id}><i/><span><b>{item.action.replaceAll('_',' ')}</b><small>{formatDate(item.timestamp)} · {item.actorRole.replace('_',' ')}</small><p>{item.detail}</p></span></div>)}{!activities.some((item)=>item.entityId===history.id)&&<p className="form-note">No recorded transitions are available for this seeded record.</p>}</div></Modal>}
  </div>;
}

function IssueModal({session,projects,assets,layers,onClose,onCreated}:{session:Session;projects:Project[];assets:Asset[];layers:GisLayer[];onClose:()=>void;onCreated:(result:{duplicate:boolean;defect:Defect})=>void}) {
  const fallback:LocatedPoint=session.tenant?.id==='tenant-nhai'?{lat:23.1462,lng:79.9341,accuracyMeters:10,source:'Demo location',address:'NH 44, Jabalpur, Madhya Pradesh',addressSource:'Demo data'}:{lat:28.6139,lng:77.2090,accuracyMeters:10,source:'Demo location',address:'Kartavya Path, New Delhi',addressSource:'Demo data'};
  const [location,setLocation]=useState<LocatedPoint>(fallback);const [form,setForm]=useState({title:'',description:'',location:fallback.address,severity:'Medium' as Defect['severity'],projectId:'' as string,assetId:'' as string});const [evidence,setEvidence]=useState<MediaEvidence[]>([]);const [saving,setSaving]=useState(false);const [locating,setLocating]=useState(false);const isCitizen=session.user.role==='citizen';
  const selectedProject=projects.find((project)=>project.id===form.projectId);const selectedAsset=assets.find((asset)=>asset.id===form.assetId);const relevantLayers=layers.filter((layer)=>layer.projectId===selectedProject?.id||layer.id===selectedAsset?.layerId||layer.projectId===null);
  async function setPoint(point:LocatedPoint){setLocation(point);setForm((current)=>({...current,location:point.address}));}
  async function locate(){setLocating(true);await setPoint(await captureDeviceLocation(fallback));setLocating(false);}
  async function select(point:{lat:number;lng:number}){await setPoint(await enrichLocation({...point,accuracyMeters:0,source:'Map selection' as const}));}
  async function submit(){setSaving(true);try{onCreated(await post<{duplicate:boolean;defect:Defect}>('/api/defects',{...form,media:evidence.map((item)=>item.id),projectId:form.projectId||null,assetId:form.assetId||null,lat:location.lat,lng:location.lng,locationAccuracyMeters:location.accuracyMeters}));}finally{setSaving(false);}}
  return <Modal
    title={isCitizen?'Report an infrastructure issue':'Raise an internal defect'}
    onClose={onClose}
    footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={submit} disabled={saving||form.title.length<4||form.description.length<8||!evidence.length}>{saving?'Checking asset and nearby issues…':'Submit geo-tagged report'}</Button></>}
  >
    <MapplsMap compact selectable onLocationSelect={select} selectedLocation={location} layers={relevantLayers} assets={selectedAsset?[selectedAsset]:[]} projects={selectedProject?[selectedProject]:[]} focus={location}/>
    <div className="geo-capture-row">
      <span><LocateFixed/><b>{location.source}</b><small>{location.address}<br/>{location.lat.toFixed(6)}, {location.lng.toFixed(6)} · ±{location.accuracyMeters} m · {location.addressSource}</small></span>
      <Button variant="secondary" onClick={locate} disabled={locating} icon={<Crosshair/>}>{locating?'Capturing GPS & address…':'Use current GPS'}</Button>
    </div>
    <div className="form-grid">
      <Field label="Issue title"><input value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} placeholder="Briefly describe the problem"/></Field>
      <Field label="Location / Mappls address"><input value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></Field>
      <Field label="Project"><select value={form.projectId} onChange={(e)=>setForm({...form,projectId:e.target.value,assetId:''})}><option value="">Not yet linked</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select></Field>
      <Field label="Underlying asset / network"><select value={form.assetId} onChange={(e)=>setForm({...form,assetId:e.target.value,projectId:assets.find((asset)=>asset.id===e.target.value)?.projectId||form.projectId})}><option value="">Select nearest asset</option>{assets.filter((asset)=>!form.projectId||asset.projectId===form.projectId).map((asset)=><option key={asset.id} value={asset.id}>{asset.name}</option>)}</select></Field>
      <Field label="Description"><textarea rows={4} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} placeholder="What did you observe?"/></Field>
      <Field label="Severity"><select value={form.severity} onChange={(e)=>setForm({...form,severity:e.target.value as Defect['severity']})}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></Field>
    </div>
    <EvidenceCapture location={location} evidence={evidence} setEvidence={setEvidence} label="Capture issue photo or video"/>
    <p className="form-note"><ShieldCheck size={15}/> Submission checks the same asset and a 300 m radius for open citizen reports. Duplicates link to the official defect and escalate visibility.</p>
  </Modal>;
}

export function PaymentsPage({session}:{session:Session}) {
  const {data,setData,loading,error}=useData<Payment[]>('/api/payments',[]);const {data:projects}=useData<Project[]>('/api/projects',[]);const {data:users}=useData<User[]>('/api/users',[]);const [modal,setModal]=useState(false);const role=session.user.role;
  async function action(p:Payment,decision:'approve'|'reject'){const updated=await post<Payment>(`/api/payments/${p.id}/action`,{decision,note:decision==='approve'?'Records verified; no deductions applicable.':'Returned for correction.'});setData(data.map((x)=>x.id===updated.id?updated:x));}
  if(loading)return <Loading label="Loading payment approval chain"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow="INVOICE TO DISBURSEMENT" title={role==='authority'?'Payment Approval':role==='checker'?'Payment Verification':'My Payment Claims'} description="Maker submits → Checker verifies against attendance and ATR → Authority authorises. Three distinct users, always." action={role==='maker'?<Button onClick={()=>setModal(true)} icon={<Plus size={17}/>}>New claim</Button>:undefined}/>
    <div className="approval-chain"><div className="done"><Wrench/><span><b>Maker</b><small>Submits invoice</small></span></div><i/><div className={role==='checker'?'current':'done'}><UserCheck/><span><b>Checker</b><small>Verifies records</small></span></div><i/><div className={role==='authority'?'current':''}><ShieldCheck/><span><b>Authority</b><small>Final authorisation</small></span></div></div>
    <div className="payment-grid">{data.map((p)=><Card className="payment-card" key={p.id}><header><div><small>{p.id}</small><h2>{p.invoiceNo}</h2></div><Badge tone={toneFor(p.status)}>{p.status}</Badge></header><strong>{formatMoney(p.amount)}</strong><div className="payment-evidence"><span><CheckCircle2/> Attendance <b>{p.attendanceReference}</b></span><span><FileCheck2/> Inspection / ATR <b>{p.inspectionReference}</b></span></div>{p.checkerNote&&<p className="review-note"><b>Checker note</b>{p.checkerNote}</p>}<footer><span>Submitted {formatDate(p.submittedAt)}</span>{role==='checker'&&p.status==='Submitted'&&<div><Button variant="ghost" onClick={()=>action(p,'reject')}>Reject</Button><Button onClick={()=>action(p,'approve')}>Verify claim</Button></div>}{role==='authority'&&p.status==='Checker Verified'&&<div><Button variant="ghost" onClick={()=>action(p,'reject')}>Reject</Button><Button onClick={()=>action(p,'approve')}>Approve & authorise</Button></div>}</footer></Card>)}</div>
    {modal&&<PaymentModal projects={projects} users={users} onClose={()=>setModal(false)} onCreated={(p)=>{setData([p,...data]);setModal(false);}}/>}</div>;
}

function PaymentModal({projects,users,onClose,onCreated}:{projects:Project[];users:User[];onClose:()=>void;onCreated:(p:Payment)=>void}){const checkers=users.filter((u)=>u.role==='checker'&&u.active),authorities=users.filter((u)=>u.role==='authority'&&u.active);const [form,setForm]=useState({projectId:projects[0]?.id||'',invoiceNo:'',checkerId:checkers[0]?.id||'',authorityId:authorities[0]?.id||'',amount:0,attendanceReference:'',inspectionReference:''});async function save(){onCreated(await post<Payment>('/api/payments',form));}return <Modal title="Submit payment claim" onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={save} disabled={!form.invoiceNo||form.amount<=0||!form.checkerId||!form.authorityId||!form.attendanceReference||!form.inspectionReference}>Submit to Checker</Button></>}><div className="form-grid"><Field label="Project"><select value={form.projectId} onChange={(e)=>setForm({...form,projectId:e.target.value})}>{projects.map((p)=><option key={p.id} value={p.id}>{p.code}</option>)}</select></Field><Field label="Invoice number"><input value={form.invoiceNo} onChange={(e)=>setForm({...form,invoiceNo:e.target.value})}/></Field><Field label="Claim amount"><input type="number" value={form.amount||''} onChange={(e)=>setForm({...form,amount:Number(e.target.value)})}/></Field><Field label="Checker"><select value={form.checkerId} onChange={(e)=>setForm({...form,checkerId:e.target.value})}>{checkers.map((u)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Authority approver"><select value={form.authorityId} onChange={(e)=>setForm({...form,authorityId:e.target.value})}>{authorities.map((u)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Attendance reference"><input value={form.attendanceReference} onChange={(e)=>setForm({...form,attendanceReference:e.target.value})} placeholder="Attendance record or period"/></Field><Field label="Inspection / ATR reference"><input value={form.inspectionReference} onChange={(e)=>setForm({...form,inspectionReference:e.target.value})} placeholder="Inspection or ATR ID"/></Field></div><p className="form-note">Budget allocation and contract management are intentionally out of scope; this prototype covers invoice-to-disbursement only.</p></Modal>}

export function CitizenPage({session}:{session:Session}) {
  const {data,setData,loading,error}=useData<Defect[]>('/api/defects',[]);const {data:gis}=useData<GisOverview>('/api/gis/overview',{configured:false,provider:'Mappls',layers:[],assets:[],defects:[],projects:[]});const [modal,setModal]=useState(false);const [duplicate,setDuplicate]=useState<Defect|null>(null);const [feedback,setFeedback]=useState<Defect|null>(null);const [rating,setRating]=useState(5);const [comment,setComment]=useState('');const [reopen,setReopen]=useState(false);const citizen=session.user.role==='citizen';
  async function submitFeedback(){if(!feedback)return;const updated=await post<Defect>(`/api/defects/${feedback.id}/feedback`,{rating,comment,reopen});setData(data.map((item)=>item.id===updated.id?updated:item));setFeedback(null);setComment('');setRating(5);setReopen(false);}
  if(loading)return <Loading label="Loading citizen issues"/>;
  if(!citizen)return <CitizenInsights defects={data}/>;
  const stages=['Under Checker Review','Assigned','In Progress','ATR Submitted','Resolved','Closed'];
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow="CITIZEN APP · MOBILE OTP" title="My Infrastructure Reports" description="Report with a location and photo, avoid duplicates, and track verified resolution end to end." action={<Button onClick={()=>setModal(true)} icon={<Plus size={17}/>}>Report an issue</Button>}/>
    {duplicate&&<div className="success-banner"><RefreshCw/><div><b>Linked to existing report {duplicate.id}</b><span>Your report increased its duplicate count and escalated severity to {duplicate.severity}.</span></div><button onClick={()=>setDuplicate(null)}><X/></button></div>}
    <div className="citizen-issue-grid">{data.map((d)=>{const index=Math.max(0,stages.indexOf(d.status));return <Card className="citizen-issue" key={d.id}><header><div><small>{d.id}</small><h2>{d.title}</h2></div><Badge tone={toneFor(d.status)}>{d.status}</Badge></header><p><MapPin size={15}/>{d.location}</p><MapplsMap compact layers={gis.layers.filter((layer)=>layer.id===gis.assets.find((asset)=>asset.id===d.assetId)?.layerId)} assets={gis.assets.filter((asset)=>asset.id===d.assetId)} defects={[d]} projects={gis.projects.filter((project)=>project.id===d.projectId)} focus={{lat:d.lat,lng:d.lng}}/><div className="status-rail">{stages.slice(0,5).map((stage,i)=><div className={i<=index?'done':''} key={stage}><i>{i<index?<Check/>:i+1}</i><span>{stage.replace('Under ','')}</span></div>)}</div><footer><span>Reported {formatDate(d.createdAt)}</span><span>{d.duplicateCount>0?`${d.duplicateCount} linked reports`:'No duplicate linked'}</span>{['Resolved','Closed'].includes(d.status)&&!d.feedback&&<Button variant="secondary" onClick={()=>setFeedback(d)} icon={<ThumbsUp/>}>Confirm resolution</Button>}{d.feedback&&<Badge tone={d.feedback.reopened?'warning':'success'}>{d.feedback.rating}/5 · {d.feedback.reopened?'Reopened':'Closed'}</Badge>}</footer></Card>})}</div>
    {modal&&<IssueModal session={session} projects={gis.projects} assets={gis.assets} layers={gis.layers} onClose={()=>setModal(false)} onCreated={(result)=>{setModal(false);if(result.duplicate)setDuplicate(result.defect);setData([result.defect,...data.filter((d)=>d.id!==result.defect.id)]);}}/>}
    {feedback&&<Modal title={`Resolution feedback · ${feedback.id}`} onClose={()=>setFeedback(null)} footer={<><Button variant="secondary" onClick={()=>setFeedback(null)}>Cancel</Button><Button onClick={submitFeedback}>{reopen?'Reopen issue':'Close issue'}</Button></>}><p className="form-note">Confirm whether the independently verified rectification solved the issue.</p><Field label="Rating"><div className="rating-row">{[1,2,3,4,5].map((value)=><button key={value} className={value<=rating?'active':''} onClick={()=>setRating(value)}>{value}</button>)}</div></Field><Field label="Comments"><textarea rows={4} value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Tell the Authority whether the resolution was satisfactory…"/></Field><label className="check-row"><input type="checkbox" checked={reopen} onChange={(e)=>setReopen(e.target.checked)}/><span><b>The issue is not resolved</b><small>Reopen it for another Maker–Checker rectification cycle.</small></span></label></Modal>}
  </div>;
}

function CitizenInsights({defects}:{defects:Defect[]}){const wards=[['Ward 7 · Central',34],['Ward 3 · Riverside',27],['Ward 12 · Industrial Area',19],['Ward 5 · Old Town',14],['Ward 9 · New Colony',8]];return <div className="page-stack"><SectionHeader eyebrow="AUTHORITY AGGREGATE DASHBOARD" title="Citizen Complaint Insights" description="Public sentiment and issue hotspots by ward, asset type and resolution state."/><div className="kpi-grid"><Card className="kpi-card"><strong>{defects.filter((d)=>d.source==='Citizen').length}</strong><span>Citizen issues in view</span></Card><Card className="kpi-card"><strong>{defects.reduce((n,d)=>n+d.duplicateCount,0)}</strong><span>Linked duplicate reports</span></Card><Card className="kpi-card"><strong>{defects.filter((d)=>d.checkerValidation==='Pending').length}</strong><span>Awaiting validation</span></Card><Card className="kpi-card"><strong>76%</strong><span>Resolved within SLA</span></Card></div><div className="dashboard-grid"><Card className="map-card span-2"><div className="card-heading"><div><MapPin/><h2>Complaint density by ward</h2></div></div><div className="hotspot-map"><span className="district d1">Ward 7<b>34</b></span><span className="district d2">Ward 3<b>27</b></span><span className="district d3">Ward 12<b>19</b></span><span className="district d4">Ward 5<b>14</b></span><span className="district d5">Ward 9<b>8</b></span></div></Card><Card><h2>Top wards by open complaints</h2><div className="ward-bars">{wards.map(([name,count])=><div key={name}><span>{name}</span><b>{count}</b><i><em style={{width:`${Number(count)*2.5}%`}}/></i></div>)}</div></Card></div></div>}

export function HelpdeskPage({session}:{session:Session}) {
  const {data,setData,loading,error}=useData<HelpdeskTicket[]>('/api/tickets',[]);const [modal,setModal]=useState(false);const [selected,setSelected]=useState<HelpdeskTicket|null>(null);const [message,setMessage]=useState('');const [faq,setFaq]=useState(0);const canManage=['authority','checker','tenant_admin'].includes(session.user.role);
  async function update(t:HelpdeskTicket,status?:HelpdeskTicket['status'],conversation?:string){const item=await patch<HelpdeskTicket>(`/api/tickets/${t.id}`,{status,message:conversation||undefined});setData(data.map((x)=>x.id===item.id?item:x));setSelected(item);}
  function nextStatus(t:HelpdeskTicket):HelpdeskTicket['status']{return t.status==='Open'||t.status==='Reopened'?'Assigned':t.status==='Assigned'?'In Progress':t.status==='In Progress'?'Resolved':'Closed';}
  if(loading)return <Loading label="Loading helpdesk"/>;
  return <div className="page-stack"><ErrorBanner message={error}/><SectionHeader eyebrow="SUPPORT + SELF SERVICE" title="Helpdesk" description="SLA-managed tickets, searchable FAQs, communications, escalation and reopen support for every user type." action={<Button onClick={()=>setModal(true)} icon={<Plus size={17}/>}>Create ticket</Button>}/><div className="dashboard-grid"><Card className="span-2"><div className="card-heading"><div><TicketCheck/><h2>{canManage?'Support queue':'My support tickets'}</h2></div></div><div className="table-wrap"><table><thead><tr><th>Ticket</th><th>Subject</th><th>Category</th><th>Priority</th><th>Status</th><th/></tr></thead><tbody>{data.map((t)=><tr key={t.id}><td><b className="mono">{t.id}</b></td><td><b>{t.subject}</b><small>Due {formatDate(t.dueAt)}</small></td><td>{t.category}</td><td><Badge tone={toneFor(t.priority)}>{t.priority}</Badge></td><td><Badge tone={toneFor(t.status)}>{t.status}</Badge></td><td><Button variant="ghost" onClick={()=>setSelected(t)}>View & respond <ArrowRight size={14}/></Button></td></tr>)}</tbody></table></div></Card><Card className="faq-card"><div className="card-heading"><div><MessageCircleQuestion/><h2>Self-serve help</h2></div></div>{['How does offline sync work?','Why was my report linked as a duplicate?','Who verifies my Action Taken Report?'].map((q,i)=><button className={faq===i?'open':''} onClick={()=>setFaq(i)} key={q}><span><HelpCircle/>{q}</span>{faq===i&&<p>{faqAnswers[i]}</p>}</button>)}</Card></div>{modal&&<TicketModal onClose={()=>setModal(false)} onCreated={(t)=>{setData([t,...data]);setModal(false);}}/>}{selected&&<Modal title={`${selected.id} · ${selected.subject}`} onClose={()=>setSelected(null)} footer={<><Button variant="secondary" onClick={()=>setSelected(null)}>Close</Button>{!canManage&&['Resolved','Closed'].includes(selected.status)&&<Button onClick={()=>update(selected,'Reopened','Resolution is not satisfactory; reopening for support.')}>Reopen</Button>}{canManage&&!['Closed'].includes(selected.status)&&<Button onClick={()=>update(selected,nextStatus(selected))}>{nextStatus(selected)}</Button>}</>}><div className="ticket-summary"><Badge tone={toneFor(selected.priority)}>{selected.priority}</Badge><Badge tone={toneFor(selected.status)}>{selected.status}</Badge><span>Due {formatDate(selected.dueAt)}</span></div><div className="conversation-list">{selected.messages?.map((item)=><div className={item.by===session.user.id?'mine':''} key={item.id}><b>{item.by===session.user.id?'You':item.by}</b><p>{item.text}</p><small>{formatDate(item.at)}</small></div>)}</div><Field label="Add update"><textarea rows={3} value={message} onChange={(e)=>setMessage(e.target.value)} placeholder="Ask a question or provide a resolution update…"/></Field><Button variant="secondary" disabled={message.trim().length<2} onClick={async()=>{await update(selected,undefined,message);setMessage('');}}>Send update</Button></Modal>}</div>;
}

function TicketModal({onClose,onCreated}:{onClose:()=>void;onCreated:(ticket:HelpdeskTicket)=>void}){const [form,setForm]=useState({category:'General',priority:'Medium' as HelpdeskTicket['priority'],subject:'',description:''});async function save(){onCreated(await post<HelpdeskTicket>('/api/tickets',form));}return <Modal title="Create support ticket" onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={save} disabled={form.subject.length<5||form.description.length<8}>Submit ticket</Button></>}><div className="form-grid"><Field label="Category"><select value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})}><option>General</option><option>Citizen App</option><option>Attendance</option><option>Inspections</option><option>Defects</option><option>Payments</option></select></Field><Field label="Priority"><select value={form.priority} onChange={(e)=>setForm({...form,priority:e.target.value as HelpdeskTicket['priority']})}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></Field><Field label="Subject"><input value={form.subject} onChange={(e)=>setForm({...form,subject:e.target.value})}/></Field><Field label="Description"><textarea rows={4} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></Field></div></Modal>}

const faqAnswers=['Field actions are stored locally when connectivity is poor. On reconnect, the server timestamp wins; conflicting local edits remain in a manual-review queue instead of being silently dropped.','Nearby open reports on the same asset are linked to one official defect. Your report still counts, raises visibility and may escalate severity.','The assigned Checker reviews your evidence and work outcome. A defect becomes resolved only after that independent verification.'];
